version: '3'
services:
  nginx-proxy:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - my_network

  hello_world:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - my_network

networks:
  my_network:
